; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Kissa Macchiato scheme by rwendell (https://github.com/rwendell/kissa)

; -- tinted-aviutl2-scheme-slug: kissa-macchiato;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=1f1c16
; ウィンドウの枠線色
WindowBorder=b8a48c
; ウィンドウ間の背景色
WindowSeparator=1f1c16
; フッターの背景色
Footer=4f6275
; フッターの進捗色
FooterProgress=834946,975250
Grouping=2a2721
GroupingHover=2e2b26
GroupingSelect=35322d
GroupingSeparator=79705f
; タイトルヘッダーの背景色
TitleHeader=47443f
BorderSelect=fef4e4
Border=d4c4a8
BorderFocus=7fa8d4
; テキストの色
Text=faf0e6
; Text=ffffff
; テキストの色(無効時)
TextDisable=b8a48c
; テキスト範囲選択色
TextSelect=7fa8d4
; ボタンの背景色
ButtonBody=33302a
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=47443f
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=d4c4a8
; ボタンの背景色(無効時)
ButtonBodyDisable=2b2822
; ボタンの背景色(選択時)
ButtonBodySelect=4f6275
; スライダーのカーソル色
SliderCursor=da9050
; スライダーのつまみの背景色
SliderThumbBody=afa28a
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=da9050
; スライダーのつまみの枠線色
SliderThumbBorder=d4c4a8
TrackBarRange=47443f40
ZoomGauge=7fa8d4
ZoomGaugeHover=6ab8b0
ZoomGaugeOff=b8a48c
ZoomGaugeOffHover=47443f
; フレーム選択範囲の色
FrameRangeSelect=7fa8d4
; フレーム選択範囲外の色
FrameRangeOutside=35322d
FrameCursor=e87777e0
FrameCursorWide=e8777780
PlayerCursor=eac67ae0
GuideLine=b8a48cc0
; レイヤーの背景色
Layer=23201a
; レイヤーの背景色(ヘッダー部分)
LayerHeader=35322d
; レイヤーの背景色(マウスが乗った時)
LayerHover=3b3832
; レイヤーの背景色(非表示)
LayerDisable=1f1c16
; レイヤーの背景色(選択時)
LayerSelect=33302a
; レイヤー範囲の背景色
LayerRange=b8a48c38
; レイヤー範囲の枠線色
LayerRangeFrame=b8a48cc8
; 映像メディアオブジェクトの色
ObjectVideo=4f6275cc,4a5b6baa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=6b8cae
; 音声メディアオブジェクトの色
ObjectAudio=834946cc,794441aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=bf6463
; 制御オブジェクトの色
ObjectControl=675871cc,605267aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=937ca7
; 映像フィルタオブジェクトの色
ObjectVideoFilter=556a43cc,50623eaa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=76985e
; 音声フィルタオブジェクトの色
ObjectAudioFilter=847148cc,7a6843aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=c1a466
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=446a63cc,40625baa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=5b9891
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=7c5633cc,735030aa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=b47844
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=fef4e4a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=e8d5b7
; オブジェクト中間点の色
ObjectSection=d4c4a8
; オブジェクト音声波形の色
ObjectWaveform=faf0e640
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=8cb870
; クリッピングオブジェクトの色(下部)
ClippingObject=6ab8b0
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=6ab8b040
; グリッド線色
GridLine=b8a48cc0
; アンカー枠色
Anchor=e8d5b7
; アンカー線色
AnchorLine=fef4e480
; アンカー枠色(開始)
AnchorIn=8cb870
; アンカー枠色(終了)
AnchorOut=e87777
; アンカー枠色(マウスが乗った時)
AnchorHover=fef4e480
; アンカー枠色(選択時)
AnchorSelect=e8d5b7
; アンカー枠の縁色
AnchorEdge=1f1c1680
; 中心点の色(グループ)
CenterGroup=8cb870
HandleX=e87777
HandleY=8cb870
HandleZ=7fa8d4
HandleXHover=e87777
HandleYHover=8cb870
HandleZHover=7fa8d4
; 表示領域外の色
OutsideDisplay=35322d
; 音声レベルメーターの色
LevelMeterRed=e87777,e8777780
LevelMeterYellow=eac67a,eac67a80
LevelMeterGreen=8cb870,8cb87080
; ログの色
LogVerbose=d4c4a8
LogInfo=faf0e6
LogScript=8cb870
LogPlugin=6ab8b0
LogWarn=eac67a
LogError=e87777

; vim: set ft=ini :
