; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; boo-shnickle-light scheme by boo-shnickle (@boo_shnickle)

; -- tinted-aviutl2-scheme-slug: boo-shnickle-light;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=ffffcc
; ウィンドウの枠線色
WindowBorder=9c9c7d
; ウィンドウ間の背景色
WindowSeparator=ffffcc
; フッターの背景色
Footer=dfdfd2
; フッターの進捗色
FooterProgress=ffdfb8,ffd8b4
Grouping=eeeebf
GroupingHover=e7e7b9
GroupingSelect=dedeb2
GroupingSeparator=bdbd97
; タイトルヘッダーの背景色
TitleHeader=bdbd97
BorderSelect=191914
Border=7c7c63
BorderFocus=bfbfd9
; テキストの色
Text=5b5b49
; Text=ffffff
; テキストの色(無効時)
TextDisable=9c9c7d
; テキスト範囲選択色
TextSelect=bfbfd9
; ボタンの背景色
ButtonBody=dedeb1
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=bdbd97
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=7c7c63
; ボタンの背景色(無効時)
ButtonBodyDisable=ececbd
; ボタンの背景色(選択時)
ButtonBodySelect=dfdfd2
; スライダーのカーソル色
SliderCursor=ffdc99
; スライダーのつまみの背景色
SliderThumbBody=969678
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=ffdc99
; スライダーのつまみの枠線色
SliderThumbBorder=7c7c63
TrackBarRange=bdbd9740
ZoomGauge=bfbfd9
ZoomGaugeHover=bfffc5
ZoomGaugeOff=9c9c7d
ZoomGaugeOffHover=bdbd97
; フレーム選択範囲の色
FrameRangeSelect=bfbfd9
; フレーム選択範囲外の色
FrameRangeOutside=dedeb2
FrameCursor=ffbfa5e0
FrameCursorWide=ffbfa580
PlayerCursor=fff299e0
GuideLine=9c9c7dc0
; レイヤーの背景色
Layer=f8f8c6
; レイヤーの背景色(ヘッダー部分)
LayerHeader=dedeb2
; レイヤーの背景色(マウスが乗った時)
LayerHover=d0d0a6
; レイヤーの背景色(非表示)
LayerDisable=ffffcc
; レイヤーの背景色(選択時)
LayerSelect=dedeb1
; レイヤー範囲の背景色
LayerRange=9c9c7d38
; レイヤー範囲の枠線色
LayerRangeFrame=9c9c7dc8
; 映像メディアオブジェクトの色
ObjectVideo=dfdfd2cc,e2e2d1aa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=cbcbd6
; 音声メディアオブジェクトの色
ObjectAudio=ffdfb8cc,ffe2baaa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=ffcbac
; 制御オブジェクトの色
ObjectControl=f8dfd2cc,f9e2d1aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=f4cbd6
; 映像フィルタオブジェクトの色
ObjectVideoFilter=f3ffb2cc,f4ffb5aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=ebffa3
; 音声フィルタオブジェクトの色
ObjectAudioFilter=fff8b2cc,fff9b5aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=fff4a3
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=dfffc8cc,e2ffc8aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=cbffc6
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=ffedb2cc,ffefb5aa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=ffe3a3
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=191914a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=3a3a2e
; オブジェクト中間点の色
ObjectSection=7c7c63
; オブジェクト音声波形の色
ObjectWaveform=5b5b4940
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=e7ff99
; クリッピングオブジェクトの色(下部)
ClippingObject=bfffc5
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=bfffc540
; グリッド線色
GridLine=9c9c7dc0
; アンカー枠色
Anchor=3a3a2e
; アンカー線色
AnchorLine=19191480
; アンカー枠色(開始)
AnchorIn=e7ff99
; アンカー枠色(終了)
AnchorOut=ffbfa5
; アンカー枠色(マウスが乗った時)
AnchorHover=19191480
; アンカー枠色(選択時)
AnchorSelect=3a3a2e
; アンカー枠の縁色
AnchorEdge=ffffcc80
; 中心点の色(グループ)
CenterGroup=e7ff99
HandleX=ffbfa5
HandleY=e7ff99
HandleZ=bfbfd9
HandleXHover=ffbfa5
HandleYHover=e7ff99
HandleZHover=bfbfd9
; 表示領域外の色
OutsideDisplay=dedeb2
; 音声レベルメーターの色
LevelMeterRed=ffbfa5,ffbfa580
LevelMeterYellow=fff299,fff29980
LevelMeterGreen=e7ff99,e7ff9980
; ログの色
LogVerbose=7c7c63
LogInfo=5b5b49
LogScript=e7ff99
LogPlugin=bfffc5
LogWarn=fff299
LogError=ffbfa5

; vim: set ft=ini :
