; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Everforest Light (Medium) scheme by Márcio Sobel (https://github.com/marciosobel)

; -- tinted-aviutl2-scheme-slug: everforest-light-medium;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=fdf6e3
; ウィンドウの枠線色
WindowBorder=939f91
; ウィンドウ間の背景色
WindowSeparator=fdf6e3
; フッターの背景色
Footer=9bc5d4
; フッターの進捗色
FooterProgress=faa59a,fa958c
Grouping=f8f3de
GroupingHover=f6f1dc
GroupingSelect=f4f0d9
GroupingSeparator=bfc3b2
; タイトルヘッダーの背景色
TitleHeader=e6e2cc
BorderSelect=2d353b
Border=829181
BorderFocus=3a94c5
; テキストの色
Text=5c6a72
; Text=ffffff
; テキストの色(無効時)
TextDisable=939f91
; テキスト範囲選択色
TextSelect=3a94c5
; ボタンの背景色
ButtonBody=f1ecd7
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=e6e2cc
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=829181
; ボタンの背景色(無効時)
ButtonBodyDisable=f8f2dd
; ボタンの背景色(選択時)
ButtonBodySelect=9bc5d4
; スライダーのカーソル色
SliderCursor=f57d26
; スライダーのつまみの背景色
SliderThumbBody=9aa594
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=f57d26
; スライダーのつまみの枠線色
SliderThumbBorder=829181
TrackBarRange=e6e2cc40
ZoomGauge=3a94c5
ZoomGaugeHover=35a77c
ZoomGaugeOff=939f91
ZoomGaugeOffHover=e6e2cc
; フレーム選択範囲の色
FrameRangeSelect=3a94c5
; フレーム選択範囲外の色
FrameRangeOutside=f4f0d9
FrameCursor=f85552e0
FrameCursorWide=f8555280
PlayerCursor=dfa000e0
GuideLine=939f91c0
; レイヤーの背景色
Layer=fbf4e1
; レイヤーの背景色(ヘッダー部分)
LayerHeader=f4f0d9
; レイヤーの背景色(マウスが乗った時)
LayerHover=ece8d2
; レイヤーの背景色(非表示)
LayerDisable=fdf6e3
; レイヤーの背景色(選択時)
LayerSelect=f1ecd7
; レイヤー範囲の背景色
LayerRange=939f9138
; レイヤー範囲の枠線色
LayerRangeFrame=939f91c8
; 映像メディアオブジェクトの色
ObjectVideo=9bc5d4cc,a5c9d5aa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=61a7cb
; 音声メディアオブジェクトの色
ObjectAudio=faa59acc,faada1aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=f9756f
; 制御オブジェクトの色
ObjectControl=eeafcecc,efb6d0aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=e585c2
; 映像フィルタオブジェクトの色
ObjectVideoFilter=c5cb72cc,cacf7daa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=a3b22e
; 音声フィルタオブジェクトの色
ObjectAudioFilter=eecb71cc,efcf7caa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=e5b12d
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=99ceafcc,a3d2b4aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=5db690
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=f9b984cc,f9bf8daa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=f6954b
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=2d353ba0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=475258
; オブジェクト中間点の色
ObjectSection=829181
; オブジェクト音声波形の色
ObjectWaveform=5c6a7240
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=8da101
; クリッピングオブジェクトの色(下部)
ClippingObject=35a77c
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=35a77c40
; グリッド線色
GridLine=939f91c0
; アンカー枠色
Anchor=475258
; アンカー線色
AnchorLine=2d353b80
; アンカー枠色(開始)
AnchorIn=8da101
; アンカー枠色(終了)
AnchorOut=f85552
; アンカー枠色(マウスが乗った時)
AnchorHover=2d353b80
; アンカー枠色(選択時)
AnchorSelect=475258
; アンカー枠の縁色
AnchorEdge=fdf6e380
; 中心点の色(グループ)
CenterGroup=8da101
HandleX=f85552
HandleY=8da101
HandleZ=3a94c5
HandleXHover=f85552
HandleYHover=8da101
HandleZHover=3a94c5
; 表示領域外の色
OutsideDisplay=f4f0d9
; 音声レベルメーターの色
LevelMeterRed=f85552,f8555280
LevelMeterYellow=dfa000,dfa00080
LevelMeterGreen=8da101,8da10180
; ログの色
LogVerbose=829181
LogInfo=5c6a72
LogScript=8da101
LogPlugin=35a77c
LogWarn=dfa000
LogError=f85552

; vim: set ft=ini :
