; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Swamp Dark scheme by Masroof Maindak (https://github.com/masroof-maindak)

; -- tinted-aviutl2-scheme-slug: swamp-dark;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=242015
; ウィンドウの枠線色
WindowBorder=5f4e41
; ウィンドウ間の背景色
WindowSeparator=242015
; フッターの背景色
Footer=724340
; フッターの進捗色
FooterProgress=7f5911,916510
Grouping=2f281c
GroupingHover=332b1f
GroupingSelect=3a3124
GroupingSeparator=6e6250
; タイトルヘッダーの背景色
TitleHeader=4d3f32
BorderSelect=f1e9d0
Border=b8a58c
BorderFocus=c1666b
; テキストの色
Text=d2c3a4
; Text=ffffff
; テキストの色(無効時)
TextDisable=5f4e41
; テキスト範囲選択色
TextSelect=c1666b
; ボタンの背景色
ButtonBody=382f23
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=4d3f32
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=b8a58c
; ボタンの背景色(無効時)
ButtonBodyDisable=30291d
; ボタンの背景色(選択時)
ButtonBodySelect=724340
; スライダーのカーソル色
SliderCursor=ebe0bb
; スライダーのつまみの背景色
SliderThumbBody=9a8a74
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=ebe0bb
; スライダーのつまみの枠線色
SliderThumbBorder=b8a58c
TrackBarRange=4d3f3240
ZoomGauge=c1666b
ZoomGaugeHover=db930d
ZoomGaugeOff=5f4e41
ZoomGaugeOffHover=4d3f32
; フレーム選択範囲の色
FrameRangeSelect=c1666b
; フレーム選択範囲外の色
FrameRangeOutside=3a3124
FrameCursor=db930de0
FrameCursorWide=db930d80
PlayerCursor=a82d56e0
GuideLine=5f4e41c0
; レイヤーの背景色
Layer=282318
; レイヤーの背景色(ヘッダー部分)
LayerHeader=3a3124
; レイヤーの背景色(マウスが乗った時)
LayerHover=403529
; レイヤーの背景色(非表示)
LayerDisable=242015
; レイヤーの背景色(選択時)
LayerSelect=382f23
; レイヤー範囲の背景色
LayerRange=5f4e4138
; レイヤー範囲の枠線色
LayerRangeFrame=5f4e41c8
; 映像メディアオブジェクトの色
ObjectVideo=724340cc,6a3f3baa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=a15859
; 音声メディアオブジェクトの色
ObjectAudio=7f5911cc,765311aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=b67c0e
; 制御オブジェクトの色
ObjectControl=5a3840cc,55353caa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=7b465a
; 映像フィルタオブジェクトの色
ObjectVideoFilter=4f4b34cc,4a4630aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=686446
; 音声フィルタオブジェクトの色
ObjectAudioFilter=662635cc,5f2532aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=8d2a49
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=7f5911cc,765311aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=b67c0e
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=878068cc,7d765faa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=c3b999
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=f1e9d0a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=ebe0bb
; オブジェクト中間点の色
ObjectSection=b8a58c
; オブジェクト音声波形の色
ObjectWaveform=d2c3a440
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=7a7653
; クリッピングオブジェクトの色(下部)
ClippingObject=db930d
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=db930d40
; グリッド線色
GridLine=5f4e41c0
; アンカー枠色
Anchor=ebe0bb
; アンカー線色
AnchorLine=f1e9d080
; アンカー枠色(開始)
AnchorIn=7a7653
; アンカー枠色(終了)
AnchorOut=db930d
; アンカー枠色(マウスが乗った時)
AnchorHover=f1e9d080
; アンカー枠色(選択時)
AnchorSelect=ebe0bb
; アンカー枠の縁色
AnchorEdge=24201580
; 中心点の色(グループ)
CenterGroup=7a7653
HandleX=db930d
HandleY=7a7653
HandleZ=c1666b
HandleXHover=db930d
HandleYHover=7a7653
HandleZHover=c1666b
; 表示領域外の色
OutsideDisplay=3a3124
; 音声レベルメーターの色
LevelMeterRed=db930d,db930d80
LevelMeterYellow=a82d56,a82d5680
LevelMeterGreen=7a7653,7a765380
; ログの色
LogVerbose=b8a58c
LogInfo=d2c3a4
LogScript=7a7653
LogPlugin=db930d
LogWarn=a82d56
LogError=db930d

; vim: set ft=ini :
