; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Kissa Latte scheme by rwendell (https://github.com/rwendell/kissa)

; -- tinted-aviutl2-scheme-slug: kissa-latte;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=f5f4f0
; ウィンドウの枠線色
WindowBorder=91887d
; ウィンドウ間の背景色
WindowSeparator=f5f4f0
; フッターの背景色
Footer=94aecc
; フッターの進捗色
FooterProgress=c99997,c08685
Grouping=eeede9
GroupingHover=ebeae6
GroupingSelect=e8e7e3
GroupingSeparator=b4b0a9
; タイトルヘッダーの背景色
TitleHeader=d5d2cb
BorderSelect=fefcfa
Border=746c62
BorderFocus=3468a8
; テキストの色
Text=1f1c16
; Text=ffffff
; テキストの色(無効時)
TextDisable=91887d
; テキスト範囲選択色
TextSelect=3468a8
; ボタンの背景色
ButtonBody=e5e3dd
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=d5d2cb
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=746c62
; ボタンの背景色(無効時)
ButtonBodyDisable=edece8
; ボタンの背景色(選択時)
ButtonBodySelect=94aecc
; スライダーのカーソル色
SliderCursor=8f5d22
; スライダーのつまみの背景色
SliderThumbBody=8d877e
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=8f5d22
; スライダーのつまみの枠線色
SliderThumbBorder=746c62
TrackBarRange=d5d2cb40
ZoomGauge=3468a8
ZoomGaugeHover=287070
ZoomGaugeOff=91887d
ZoomGaugeOffHover=d5d2cb
; フレーム選択範囲の色
FrameRangeSelect=3468a8
; フレーム選択範囲外の色
FrameRangeOutside=e8e7e3
FrameCursor=9e3e3ee0
FrameCursorWide=9e3e3e80
PlayerCursor=7d6820e0
GuideLine=91887dc0
; レイヤーの背景色
Layer=f2f1ed
; レイヤーの背景色(ヘッダー部分)
LayerHeader=e8e7e3
; レイヤーの背景色(マウスが乗った時)
LayerHover=dedcd6
; レイヤーの背景色(非表示)
LayerDisable=f5f4f0
; レイヤーの背景色(選択時)
LayerSelect=e5e3dd
; レイヤー範囲の背景色
LayerRange=91887d38
; レイヤー範囲の枠線色
LayerRangeFrame=91887dc8
; 映像メディアオブジェクトの色
ObjectVideo=94aecccc,9eb5cfaa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=5a84b6
; 音声メディアオブジェクトの色
ObjectAudio=c99997cc,cda29faa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=af6261
; 制御オブジェクトの色
ObjectControl=ac96c8cc,b39fccaa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=815db0
; 映像フィルタオブジェクトの色
ObjectVideoFilter=96b2a0cc,9fb8a8aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=5d8a70
; 音声フィルタオブジェクトの色
ObjectAudioFilter=b9ae88cc,bfb592aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=958449
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=8eb2b0cc,98b8b6aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=518a89
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=c2a889cc,c7b093aa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=a37b4b
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=fefcfaa0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=6e6459
; オブジェクト中間点の色
ObjectSection=746c62
; オブジェクト音声波形の色
ObjectWaveform=1f1c1640
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=387050
; クリッピングオブジェクトの色(下部)
ClippingObject=287070
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=28707040
; グリッド線色
GridLine=91887dc0
; アンカー枠色
Anchor=6e6459
; アンカー線色
AnchorLine=fefcfa80
; アンカー枠色(開始)
AnchorIn=387050
; アンカー枠色(終了)
AnchorOut=9e3e3e
; アンカー枠色(マウスが乗った時)
AnchorHover=fefcfa80
; アンカー枠色(選択時)
AnchorSelect=6e6459
; アンカー枠の縁色
AnchorEdge=f5f4f080
; 中心点の色(グループ)
CenterGroup=387050
HandleX=9e3e3e
HandleY=387050
HandleZ=3468a8
HandleXHover=9e3e3e
HandleYHover=387050
HandleZHover=3468a8
; 表示領域外の色
OutsideDisplay=e8e7e3
; 音声レベルメーターの色
LevelMeterRed=9e3e3e,9e3e3e80
LevelMeterYellow=7d6820,7d682080
LevelMeterGreen=387050,38705080
; ログの色
LogVerbose=746c62
LogInfo=1f1c16
LogScript=387050
LogPlugin=287070
LogWarn=7d6820
LogError=9e3e3e

; vim: set ft=ini :
