; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Embers Light scheme by Jannik Siebert (https://github.com/janniks)

; -- tinted-aviutl2-scheme-slug: embers-light;
; -- tinted-aviutl2-base-template: rainbow;

[Color]
; デフォルトの背景色
Background=dbd6d1
; ウィンドウの枠線色
WindowBorder=8a8075
; ウィンドウ間の背景色
WindowSeparator=dbd6d1
; フッターの背景色
Footer=a496a9
; フッターの進捗色
FooterProgress=aea194,a59787
Grouping=ccc6bf
GroupingHover=c6bfb8
GroupingSelect=beb6ae
GroupingSeparator=9a938c
; タイトルヘッダーの背景色
TitleHeader=a39a90
BorderSelect=16130f
Border=5a5047
BorderFocus=6d5782
; テキストの色
Text=433b32
; Text=ffffff
; テキストの色(無効時)
TextDisable=8a8075
; テキスト範囲選択色
TextSelect=6d5782
; ボタンの背景色
ButtonBody=bfb8b0
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=a39a90
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=5a5047
; ボタンの背景色(無効時)
ButtonBodyDisable=cbc4bd
; ボタンの背景色(選択時)
ButtonBodySelect=a496a9
; スライダーのカーソル色
SliderCursor=828257
; スライダーのつまみの背景色
SliderThumbBody=736a62
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=828257
; スライダーのつまみの枠線色
SliderThumbBorder=5a5047
TrackBarRange=a39a9040
ZoomGauge=6d5782
ZoomGaugeHover=576d82
ZoomGaugeOff=8a8075
ZoomGaugeOffHover=a39a90
; フレーム選択範囲の色
FrameRangeSelect=6d5782
; フレーム選択範囲外の色
FrameRangeOutside=beb6ae
FrameCursor=826d57e0
FrameCursorWide=826d5780
PlayerCursor=6d8257e0
GuideLine=8a8075c0
; レイヤーの背景色
Layer=d5cfca
; レイヤーの背景色(ヘッダー部分)
LayerHeader=beb6ae
; レイヤーの背景色(マウスが乗った時)
LayerHover=b3aca3
; レイヤーの背景色(非表示)
LayerDisable=dbd6d1
; レイヤーの背景色(選択時)
LayerSelect=bfb8b0
; レイヤー範囲の背景色
LayerRange=8a807538
; レイヤー範囲の枠線色
LayerRangeFrame=8a8075c8
; 映像メディアオブジェクトの色
ObjectVideo=a496a9cc,a99cadaa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=837091
; 音声メディアオブジェクトの色
ObjectAudio=aea194cc,b2a69aaa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=93826f
; 制御オブジェクトの色
ObjectControl=ae969fcc,b29ca4aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=937081
; 映像フィルタオブジェクトの色
ObjectVideoFilter=99ac9fcc,9fb0a4aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=719281
; 音声フィルタオブジェクトの色
ObjectAudioFilter=a4ac94cc,a9b09aaa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=83926f
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=99a1a9cc,9fa6adaa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=718291
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=aeac94cc,b2b09aaa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=93926f
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=16130fa0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=2c2620
; オブジェクト中間点の色
ObjectSection=5a5047
; オブジェクト音声波形の色
ObjectWaveform=433b3240
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=57826d
; クリッピングオブジェクトの色(下部)
ClippingObject=576d82
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=576d8240
; グリッド線色
GridLine=8a8075c0
; アンカー枠色
Anchor=2c2620
; アンカー線色
AnchorLine=16130f80
; アンカー枠色(開始)
AnchorIn=57826d
; アンカー枠色(終了)
AnchorOut=826d57
; アンカー枠色(マウスが乗った時)
AnchorHover=16130f80
; アンカー枠色(選択時)
AnchorSelect=2c2620
; アンカー枠の縁色
AnchorEdge=dbd6d180
; 中心点の色(グループ)
CenterGroup=57826d
HandleX=826d57
HandleY=57826d
HandleZ=6d5782
HandleXHover=826d57
HandleYHover=57826d
HandleZHover=6d5782
; 表示領域外の色
OutsideDisplay=beb6ae
; 音声レベルメーターの色
LevelMeterRed=826d57,826d5780
LevelMeterYellow=6d8257,6d825780
LevelMeterGreen=57826d,57826d80
; ログの色
LogVerbose=5a5047
LogInfo=433b32
LogScript=57826d
LogPlugin=576d82
LogWarn=6d8257
LogError=826d57

; vim: set ft=ini :
