; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; boo-shnickle scheme by boo-shnickle (@boo_shnickle)

; -- tinted-aviutl2-scheme-slug: boo-shnickle;
; -- tinted-aviutl2-base-template: original;

[Color]
; デフォルトの背景色
Background=191914
; ウィンドウの枠線色
WindowBorder=7c7c63
; ウィンドウ間の背景色
WindowSeparator=191914
; フッターの背景色
Footer=6c6c76
; フッターの進捗色
FooterProgress=8c6c5c,a37c6b
Grouping=292921
GroupingHover=303026
GroupingSelect=3a3a2e
GroupingSeparator=5a5a48
; タイトルヘッダーの背景色
TitleHeader=5b5b49
BorderSelect=ffffcc
Border=9c9c7d
BorderFocus=bfbfd9
; テキストの色
Text=bdbd97
; Text=ffffff
; テキストの色(無効時)
TextDisable=7c7c63
; テキスト範囲選択色
TextSelect=bfbfd9
; ボタンの背景色
ButtonBody=3a3a2e
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=5b5b49
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=9c9c7d
; ボタンの背景色(無効時)
ButtonBodyDisable=2b2b22
; ボタンの背景色(選択時)
ButtonBodySelect=6c6c76
; スライダーのカーソル色
SliderCursor=ffdc99
; スライダーのつまみの背景色
SliderThumbBody=818168
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=ffdc99
; スライダーのつまみの枠線色
SliderThumbBorder=9c9c7d
TrackBarRange=5b5b4940
ZoomGauge=bfbfd9
ZoomGaugeHover=bfffc5
ZoomGaugeOff=7c7c63
ZoomGaugeOffHover=5b5b49
; フレーム選択範囲の色
FrameRangeSelect=bfbfd9
; フレーム選択範囲外の色
FrameRangeOutside=3a3a2e
FrameCursor=ffbfa5e0
FrameCursorWide=ffbfa580
PlayerCursor=fff299e0
GuideLine=7c7c63c0
; レイヤーの背景色
Layer=1f1f19
; レイヤーの背景色(ヘッダー部分)
LayerHeader=3a3a2e
; レイヤーの背景色(マウスが乗った時)
LayerHover=474739
; レイヤーの背景色(非表示)
LayerDisable=191914
; レイヤーの背景色(選択時)
LayerSelect=3a3a2e
; レイヤー範囲の背景色
LayerRange=7c7c6338
; レイヤー範囲の枠線色
LayerRangeFrame=7c7c63c8
; 映像メディアオブジェクトの色
ObjectVideo=6c6c76cc,63636caa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=9d9db1
; 音声メディアオブジェクトの色
ObjectAudio=8c6c5ccc,806355aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=d19d88
; 制御オブジェクトの色
ObjectControl=6c8c6ccc,638063aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=9dd1a1
; 映像フィルタオブジェクトの色
ObjectVideoFilter=808c56cc,75804faa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=bdd17e
; 音声フィルタオブジェクトの色
ObjectAudioFilter=8c8556cc,807a4faa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=d1c67e
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=6c8c6ccc,638063aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=9dd1a1
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=6c8c6ccc,638063aa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=9dd1a1
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=ffffcca0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=dedeb2
; オブジェクト中間点の色
ObjectSection=9c9c7d
; オブジェクト音声波形の色
ObjectWaveform=bdbd9740
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=e7ff99
; クリッピングオブジェクトの色(下部)
ClippingObject=bfffc5
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=bfffc540
; グリッド線色
GridLine=7c7c63c0
; アンカー枠色
Anchor=dedeb2
; アンカー線色
AnchorLine=ffffcc80
; アンカー枠色(開始)
AnchorIn=e7ff99
; アンカー枠色(終了)
AnchorOut=ffbfa5
; アンカー枠色(マウスが乗った時)
AnchorHover=ffffcc80
; アンカー枠色(選択時)
AnchorSelect=dedeb2
; アンカー枠の縁色
AnchorEdge=19191480
; 中心点の色(グループ)
CenterGroup=e7ff99
HandleX=ffbfa5
HandleY=e7ff99
HandleZ=bfbfd9
HandleXHover=ffbfa5
HandleYHover=e7ff99
HandleZHover=bfbfd9
; 表示領域外の色
OutsideDisplay=3a3a2e
; 音声レベルメーターの色
LevelMeterRed=ffbfa5,ffbfa580
LevelMeterYellow=fff299,fff29980
LevelMeterGreen=e7ff99,e7ff9980
; ログの色
LogVerbose=9c9c7d
LogInfo=bdbd97
LogScript=e7ff99
LogPlugin=bfffc5
LogWarn=fff299
LogError=ffbfa5

; vim: set ft=ini :
