; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Everforest Light (Hard) scheme by Márcio Sobel (https://github.com/marciosobel)

; -- tinted-aviutl2-scheme-slug: everforest-light-hard;
; -- tinted-aviutl2-base-template: original;

[Color]
; デフォルトの背景色
Background=fffbef
; ウィンドウの枠線色
WindowBorder=939f91
; ウィンドウ間の背景色
WindowSeparator=fffbef
; フッターの背景色
Footer=9cc7da
; フッターの進捗色
FooterProgress=fba8a0,fa9790
Grouping=fbf8e9
GroupingHover=faf6e7
GroupingSelect=f8f5e4
GroupingSeparator=c0c6b8
; タイトルヘッダーの背景色
TitleHeader=edeada
BorderSelect=272e33
Border=829181
BorderFocus=3a94c5
; テキストの色
Text=5c6a72
; Text=ffffff
; テキストの色(無効時)
TextDisable=939f91
; テキスト範囲選択色
TextSelect=3a94c5
; ボタンの背景色
ButtonBody=f6f2e4
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=edeada
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=829181
; ボタンの背景色(無効時)
ButtonBodyDisable=fbf7e8
; ボタンの背景色(選択時)
ButtonBodySelect=9cc7da
; スライダーのカーソル色
SliderCursor=f57d26
; スライダーのつまみの背景色
SliderThumbBody=9ba697
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=f57d26
; スライダーのつまみの枠線色
SliderThumbBorder=829181
TrackBarRange=edeada40
ZoomGauge=3a94c5
ZoomGaugeHover=35a77c
ZoomGaugeOff=939f91
ZoomGaugeOffHover=edeada
; フレーム選択範囲の色
FrameRangeSelect=3a94c5
; フレーム選択範囲外の色
FrameRangeOutside=f8f5e4
FrameCursor=f85552e0
FrameCursorWide=f8555280
PlayerCursor=dfa000e0
GuideLine=939f91c0
; レイヤーの背景色
Layer=fdf9ec
; レイヤーの背景色(ヘッダー部分)
LayerHeader=f8f5e4
; レイヤーの背景色(マウスが乗った時)
LayerHover=f2efe0
; レイヤーの背景色(非表示)
LayerDisable=fffbef
; レイヤーの背景色(選択時)
LayerSelect=f6f2e4
; レイヤー範囲の背景色
LayerRange=939f9138
; レイヤー範囲の枠線色
LayerRangeFrame=939f91c8
; 映像メディアオブジェクトの色
ObjectVideo=9cc7dacc,a6ccdcaa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=61a8cd
; 音声メディアオブジェクトの色
ObjectAudio=fba8a0cc,fbb0a8aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=f97671
; 制御オブジェクトの色
ObjectControl=9ad1b5cc,a4d5bbaa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=5db793
; 映像フィルタオブジェクトの色
ObjectVideoFilter=c6ce78cc,cbd283aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=a3b330
; 音声フィルタオブジェクトの色
ObjectAudioFilter=efcd77cc,f0d283aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=e5b22f
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=9ad1b5cc,a4d5bbaa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=5db793
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=9ad1b5cc,a4d5bbaa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=5db793
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=272e33a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=414b50
; オブジェクト中間点の色
ObjectSection=829181
; オブジェクト音声波形の色
ObjectWaveform=5c6a7240
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=8da101
; クリッピングオブジェクトの色(下部)
ClippingObject=35a77c
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=35a77c40
; グリッド線色
GridLine=939f91c0
; アンカー枠色
Anchor=414b50
; アンカー線色
AnchorLine=272e3380
; アンカー枠色(開始)
AnchorIn=8da101
; アンカー枠色(終了)
AnchorOut=f85552
; アンカー枠色(マウスが乗った時)
AnchorHover=272e3380
; アンカー枠色(選択時)
AnchorSelect=414b50
; アンカー枠の縁色
AnchorEdge=fffbef80
; 中心点の色(グループ)
CenterGroup=8da101
HandleX=f85552
HandleY=8da101
HandleZ=3a94c5
HandleXHover=f85552
HandleYHover=8da101
HandleZHover=3a94c5
; 表示領域外の色
OutsideDisplay=f8f5e4
; 音声レベルメーターの色
LevelMeterRed=f85552,f8555280
LevelMeterYellow=dfa000,dfa00080
LevelMeterGreen=8da101,8da10180
; ログの色
LogVerbose=829181
LogInfo=5c6a72
LogScript=8da101
LogPlugin=35a77c
LogWarn=dfa000
LogError=f85552

; vim: set ft=ini :
