; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Swamp Light scheme by Masroof Maindak (https://github.com/masroof-maindak)

; -- tinted-aviutl2-scheme-slug: swamp-light;
; -- tinted-aviutl2-base-template: original;

[Color]
; デフォルトの背景色
Background=f1e3d1
; ウィンドウの枠線色
WindowBorder=b5a492
; ウィンドウ間の背景色
WindowSeparator=f1e3d1
; フッターの背景色
Footer=d8aea5
; フッターの進捗色
FooterProgress=e0bd68,ddb553
Grouping=e7d8c6
GroupingHover=e3d4c2
GroupingSelect=ddcebc
GroupingSeparator=c8b9a7
; タイトルヘッダーの背景色
TitleHeader=c9b9a7
BorderSelect=8c7b68
Border=a0907d
BorderFocus=bf7979
; テキストの色
Text=64513e
; Text=ffffff
; テキストの色(無効時)
TextDisable=b5a492
; テキスト範囲選択色
TextSelect=bf7979
; ボタンの背景色
ButtonBody=ddcebc
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=c9b9a7
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=a0907d
; ボタンの背景色(無効時)
ButtonBodyDisable=e6d7c5
; ボタンの背景色(選択時)
ButtonBodySelect=d8aea5
; スライダーのカーソル色
SliderCursor=64513e
; スライダーのつまみの背景色
SliderThumbBody=b0a08d
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=64513e
; スライダーのつまみの枠線色
SliderThumbBorder=a0907d
TrackBarRange=c9b9a740
ZoomGauge=bf7979
ZoomGaugeHover=d09700
ZoomGaugeOff=b5a492
ZoomGaugeOffHover=c9b9a7
; フレーム選択範囲の色
FrameRangeSelect=bf7979
; フレーム選択範囲外の色
FrameRangeOutside=ddcebc
FrameCursor=d09700e0
FrameCursorWide=d0970080
PlayerCursor=993333e0
GuideLine=b5a492c0
; レイヤーの背景色
Layer=eddecc
; レイヤーの背景色(ヘッダー部分)
LayerHeader=ddcebc
; レイヤーの背景色(マウスが乗った時)
LayerHover=d5c5b3
; レイヤーの背景色(非表示)
LayerDisable=f1e3d1
; レイヤーの背景色(選択時)
LayerSelect=ddcebc
; レイヤー範囲の背景色
LayerRange=b5a49238
; レイヤー範囲の枠線色
LayerRangeFrame=b5a492c8
; 映像メディアオブジェクトの色
ObjectVideo=d8aea5cc,dab3a9aa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=c98e8a
; 音声メディアオブジェクトの色
ObjectAudio=e0bd68cc,e2c072aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=d6a629
; 制御オブジェクトの色
ObjectControl=e0bd68cc,e2c072aa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=d6a629
; 映像フィルタオブジェクトの色
ObjectVideoFilter=c0b89dcc,c5bca2aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=a39e7e
; 音声フィルタオブジェクトの色
ObjectAudioFilter=c58b82cc,c99389aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=aa5652
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=e0bd68cc,e2c072aa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=d6a629
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=e0bd68cc,e2c072aa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=d6a629
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=8c7b68a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=786653
; オブジェクト中間点の色
ObjectSection=a0907d
; オブジェクト音声波形の色
ObjectWaveform=64513e40
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=908d6a
; クリッピングオブジェクトの色(下部)
ClippingObject=d09700
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=d0970040
; グリッド線色
GridLine=b5a492c0
; アンカー枠色
Anchor=786653
; アンカー線色
AnchorLine=8c7b6880
; アンカー枠色(開始)
AnchorIn=908d6a
; アンカー枠色(終了)
AnchorOut=d09700
; アンカー枠色(マウスが乗った時)
AnchorHover=8c7b6880
; アンカー枠色(選択時)
AnchorSelect=786653
; アンカー枠の縁色
AnchorEdge=f1e3d180
; 中心点の色(グループ)
CenterGroup=908d6a
HandleX=d09700
HandleY=908d6a
HandleZ=bf7979
HandleXHover=d09700
HandleYHover=908d6a
HandleZHover=bf7979
; 表示領域外の色
OutsideDisplay=ddcebc
; 音声レベルメーターの色
LevelMeterRed=d09700,d0970080
LevelMeterYellow=993333,99333380
LevelMeterGreen=908d6a,908d6a80
; ログの色
LogVerbose=a0907d
LogInfo=64513e
LogScript=908d6a
LogPlugin=d09700
LogWarn=993333
LogError=d09700

; vim: set ft=ini :
