; tinted-aviutl2 (https://github.com/sevenc-nanashi/tinted-aviutl2)
; by Nanashi.
; Everforest Light (Soft) scheme by Márcio Sobel (https://github.com/marciosobel)

; -- tinted-aviutl2-scheme-slug: everforest-light-soft;
; -- tinted-aviutl2-base-template: original;

[Color]
; デフォルトの背景色
Background=f3ead3
; ウィンドウの枠線色
WindowBorder=939f91
; ウィンドウ間の背景色
WindowSeparator=f3ead3
; フッターの背景色
Footer=96bfcc
; フッターの進捗色
FooterProgress=f59f92,f69085
Grouping=eee7ce
GroupingHover=ece5cc
GroupingSelect=eae4ca
GroupingSeparator=babdaa
; タイトルヘッダーの背景色
TitleHeader=ddd8be
BorderSelect=333c43
Border=829181
BorderFocus=3a94c5
; テキストの色
Text=5c6a72
; Text=ffffff
; テキストの色(無効時)
TextDisable=939f91
; テキスト範囲選択色
TextSelect=3a94c5
; ボタンの背景色
ButtonBody=e8e1c8
; ボタンの背景色(マウスが乗った時)
ButtonBodyHover=ddd8be
; ボタンの背景色(マウスを押している時)
ButtonBodyPress=829181
; ボタンの背景色(無効時)
ButtonBodyDisable=eee6ce
; ボタンの背景色(選択時)
ButtonBodySelect=96bfcc
; スライダーのカーソル色
SliderCursor=f57d26
; スライダーのつまみの背景色
SliderThumbBody=98a291
; スライダーのつまみの背景色(フォーカス時)
SliderThumbBodyFocus=f57d26
; スライダーのつまみの枠線色
SliderThumbBorder=829181
TrackBarRange=ddd8be40
ZoomGauge=3a94c5
ZoomGaugeHover=35a77c
ZoomGaugeOff=939f91
ZoomGaugeOffHover=ddd8be
; フレーム選択範囲の色
FrameRangeSelect=3a94c5
; フレーム選択範囲外の色
FrameRangeOutside=eae4ca
FrameCursor=f85552e0
FrameCursorWide=f8555280
PlayerCursor=dfa000e0
GuideLine=939f91c0
; レイヤーの背景色
Layer=f1e8d1
; レイヤーの背景色(ヘッダー部分)
LayerHeader=eae4ca
; レイヤーの背景色(マウスが乗った時)
LayerHover=e3ddc4
; レイヤーの背景色(非表示)
LayerDisable=f3ead3
; レイヤーの背景色(選択時)
LayerSelect=e8e1c8
; レイヤー範囲の背景色
LayerRange=939f9138
; レイヤー範囲の枠線色
LayerRangeFrame=939f91c8
; 映像メディアオブジェクトの色
ObjectVideo=96bfcccc,9fc3ccaa
; 映像メディアオブジェクトの色(選択時)
ObjectVideoSelect=5fa5c7
; 音声メディアオブジェクトの色
ObjectAudio=f59f92cc,f5a698aa
; 音声メディアオブジェクトの色(選択時)
ObjectAudioSelect=f7726b
; 制御オブジェクトの色
ObjectControl=94c8a7cc,9dcbabaa
; 制御オブジェクトの色(選択時)
ObjectControlSelect=5bb48d
; 映像フィルタオブジェクトの色
ObjectVideoFilter=c0c56acc,c5c974aa
; 映像フィルタオブジェクトの色(選択時)
ObjectVideoFilterSelect=a1af2b
; 音声フィルタオブジェクトの色
ObjectAudioFilter=e9c569cc,eac874aa
; 音声フィルタオブジェクトの色(選択時)
ObjectAudioFilterSelect=e3ae2a
; 映像フィルタ効果オブジェクトの色
ObjectVideoEffect=94c8a7cc,9dcbabaa
; 映像フィルタ効果オブジェクトの色(選択時)
ObjectVideoEffectSelect=5bb48d
; 音声フィルタ効果オブジェクトの色
ObjectAudioEffect=94c8a7cc,9dcbabaa
; 音声フィルタ効果オブジェクトの色(選択時)
ObjectAudioEffectSelect=5bb48d
; オブジェクトの枠色(マウスが乗った時)
ObjectHover=333c43a0
; オブジェクトの枠色(フォーカス時)
ObjectFocus=4d5960
; オブジェクト中間点の色
ObjectSection=829181
; オブジェクト音声波形の色
ObjectWaveform=5c6a7240
; 仮想バッファ出力オブジェクトの色(下部)
ObjectTempBuffer=8da101
; クリッピングオブジェクトの色(下部)
ClippingObject=35a77c
; クリッピングオブジェクトの視覚化時の色
ClippingObjectMask=35a77c40
; グリッド線色
GridLine=939f91c0
; アンカー枠色
Anchor=4d5960
; アンカー線色
AnchorLine=333c4380
; アンカー枠色(開始)
AnchorIn=8da101
; アンカー枠色(終了)
AnchorOut=f85552
; アンカー枠色(マウスが乗った時)
AnchorHover=333c4380
; アンカー枠色(選択時)
AnchorSelect=4d5960
; アンカー枠の縁色
AnchorEdge=f3ead380
; 中心点の色(グループ)
CenterGroup=8da101
HandleX=f85552
HandleY=8da101
HandleZ=3a94c5
HandleXHover=f85552
HandleYHover=8da101
HandleZHover=3a94c5
; 表示領域外の色
OutsideDisplay=eae4ca
; 音声レベルメーターの色
LevelMeterRed=f85552,f8555280
LevelMeterYellow=dfa000,dfa00080
LevelMeterGreen=8da101,8da10180
; ログの色
LogVerbose=829181
LogInfo=5c6a72
LogScript=8da101
LogPlugin=35a77c
LogWarn=dfa000
LogError=f85552

; vim: set ft=ini :
